#!/usr/bin/env bash
# Digs into DNS records
# shellcheck disable=SC2086

DOMAIN=$1
SUB_DOMAIN=$2

print_all () {
	dig www."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk '/www/{print "The subdomain www is a " $4 " record and points to " $5}'
	dig lb-01."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk '/lb-01/{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
	dig web-01."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk '/web-01/{print "The subdomain web-01 is a " $4 " record and points to " $5}'
	dig web-02."$DOMAIN" | grep -A1 'ANSWER SECTION:' | awk '/web-02/{print "The subdomain web-02 is a " $4 " record and points to " $5}'
}

if [ $# -eq 1 ]; then
	print_all
else
	RECORD_TYPE=$(dig "$SUB_DOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	DESTINATION=$(dig "$SUB_DOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
	echo "The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
fi
