#!/usr/bin/env bash
# Configures Nginx with custom HTTP response
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install Nginx -y
sudo sed -i "s/^\(\slocation \/ {\)$/\1\n\t\tadd_header X-Served-By: $HOSTNAME;/" /etc/nginx/sites-available/default
sudo service nginx restart
