#!/usr/bin/env bash
#Creates backup of mysql database

PASS="$1"

if [ -z $PASS ]; then
	sudo mysqldump -uroot --all-databases --events > backup.sql
else
	sudo mysqldump -uroot -p"$PASS" --all-databases --events > backup.sql
fi

tar cfz $(date +%d-%m-%y).tar.gz backup.sql
