#!/usr/bin/env bash
#Displays 'To infinity and beyond' indefinitely, and 'I am invincible!!!'.

echo "$$" > /var/run/holbertonscript.pid

while true; do
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap break SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done

rm /var/run/holbertonscript.pid
