#!/usr/bin/env bash
#Displays "Holberton School" 10 times, 4 is "bad luck", 8 is "good luck".

i=1
while [ $i -lt 11 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck";
	elif [ $i -eq 8 ]; then
		echo "good luck";
	else
		echo "Holberton School";
	fi
	((i += 1));
done
