#!/usr/bin/env bash
# Installs nginx, and creates a redirect page

sudo apt-get update
sudo apt-get install Nginx -y
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "s/^\slocation \/ {$/\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/youtu.be\/Sagg08DrO5U;\n\t}\n\n\tlocation \/ {/" /etc/nginx/sites-available/default
sudo service nginx restart
