#!/usr/bin/env bash
# Reconfigures some IP address resolutions on an Ubuntu server.
grep -Pv "localhost" /etc/hosts > /tmp/tmp_hosts; echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" >> /tmp/tmp_hosts; cat /tmp/tmp_hosts > /etc/hosts
